name: Nightly Python Job

on:
  schedule:
  #- cron: "0 0 * * *"   # Runs every night at 00:00 UTC
  cron: "*/5 * * * *"
jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script
        run: python main.py
